version: '3'
services:
  front-end: 
    build: .
    container_name: front-end
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 3000
    ports:
      - 3000:80

  twitter: 
    build: ../magic-mirror-twitter/
    container_name: twitter
    env_file: ../magic-mirror-twitter/.env
    expose:
      - 5050